codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
  precision: 1
  round: down
  range: 0..100

ignore:
  - scripts/**
  - pkg/utils/** # optional: adjust if you don't want to ignore

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true