codecov:
  require_ci_to_pass: true

coverage:
  precision: 1
  round: down
  range: 0..100
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

# Exclude helper scripts and non-library code from coverage stats
ignore:
  - scripts/**
