replicaCount: 1

image:
  repository: my-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

env: {}

serviceAccount:
  create: false

# Metrics discovery config for Prometheus (non-operator)
metrics:
  path: /metrics
  # default port follows service.port; override to force a different scrape port
  port: ""

# Toggle ServiceMonitor when Prometheus Operator is installed
prometheusOperator:
  enabled: false
