apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "example-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.metrics.path | default "/metrics" | quote }}
    prometheus.io/port: {{ .Values.metrics.port | default .Values.service.port | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "example-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
