name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Go test
        run: go test ./...
      - name: Generate grafana values
        run: go run ./scripts/generate-grafana-values > grafana-ci-values.yaml
      - name: Helm template grafana
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm template graf grafana/grafana -n monitoring -f grafana-ci-values.yaml --include-crds
