name: Test coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Run tests and update coverage badge
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Run tests and generate coverage
        run: |
          # Generate coverage profile for Codecov (coverage.txt) and a func summary (coverage.out)
          go test -v ./... -covermode=count -coverprofile=coverage.txt
          # also produce the func-summary file for local scripts/tools compatibility
          go tool cover -func=coverage.txt -o=coverage.out

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.txt
            coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: >-
          ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
          flags: unittests
          fail_ci_if_error: false
          verbose: true
